[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Open Contact Book"
authors = [{name = "Open Contact Book", email = "contact@aurelienpierre"}]
dynamic = ["version", "description"]
